import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Leaf } from "@/components/leaf";
import { Navbar } from "@/components/navbar";
import { Logo } from "@/components/logo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Root Up Growth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-amber-50`}
      >
        <header className="flex justify-between w-full h-50" role="banner">
          <Leaf />
          <Navbar />
          <Logo />
        </header>

        
        <main id="main-content" role="main" className="min-h-screen">
          {children}
        </main>

      </body>
    </html>
  );
}
